

/*Suppresion des anciennes tables*/
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS DISCOUNT_CODE;
DROP TABLE IF EXISTS MANUFACTURER;
DROP TABLE IF EXISTS MICRO_MARKET;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PRODUCT_CODE;
DROP TABLE IF EXISTS PURCHASE_ORDER;

/*Création des nouvelles tables pour les tests*/
CREATE TABLE CUSTOMER(
    CUSTOMER_ID INTEGER PRIMARY KEY,
    FOREIGN KEY (DISCOUNT_CODE) REFERENCES DISCOUNT_CODE(DISCOUNT_CODE),
    FOREIGN KEY (ZIP) REFERENCES DISCOUNT_CODE(DISCOUNT_CODE),
    NAME VARCHAR(30),
    ADDRESSLINE1 VARCHAR(30),
    ADDRESSLINE2 VARCHAR(30),
    CITY VARCHAR(25),
    STATE VARCHAR(2),
    PHONE VARCHAR(12),
    FAX VARCHAR(12),
    EMAIL VARCHAR(40),
    CREDIT_LIMIT VARCHAR(10));

CREATE TABLE DISCOUNT_CODE(
    DISCOUNT_CODE CHAR PRIMARY KEY,
    RATE DECIMAL(4,2));

CREATE TABLE MANUFACTURER(
    MANUFACTURER_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(30),
    ADDRESSLINE1 VARCHAR(30),
    ADDRESSLINE2 VARCHAR(30),
    CITY VARCHAR(25),
    STATE VARCHAR(2),
    ZIP CHAR(10),
    PHONE VARCHAR(12),
    FAX VARCHAR(12),
    EMAIL VARCHAR(40),
    REP VARCHAR(30));

CREATE TABLE MICRO_MARKET(
    ZIP_CODE VARCHAR PRIMARY KEY,
    RADIUS DOUBLE(52),
    AREA_LENGTH DOUBLE(52),
    AREA_WIDTH DOUBLE(52));

CREATE TABLE PRODUCT(
    PRODUCT_ID INTEGER PRIMARY KEY,
    FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER(MANUFACTURER_ID),
    FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCT_CODE(PROD_CODE),
    PURCHASE_COST DECIMAL(12,2),
    QUANTITY_ON_HAND INTEGER(10),
    MARKUP DECIMAL(4,2),
    AVAILABLE VARCHAR(5),
    DESCRIPTION VARCHAR(50));

CREATE PRODUCT_CODE(
    PROD_CODE CHAR PRIMARY KEY,
    DISCOUNT_CODE CHAR(1),
    DESCRIPTION VARCHAR(10));

CREATE PURCHASE_ORDER(
    ORDER_NUM INTEGER PRIMARY KEY,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    QUANTITY SMALLINT(5),
    SHIPPING_COST DECIMAL(12),
    SALES_DATE DATE,
    SHIPPING_DATE DATE,
    FREIGHT_COMPANY VARCHAR(30));

/*Ajout de quelques exemples des les tables pour les tests*/
INSERT INTO CUSTOMER VALUES(10,'N',95100,'Apple','1. Apple Park Way','Apple Park','Cupertino','CA',305-555-0001,305-555-0011,'apple@example.com',500);
INSERT INTO CUSTOMER VALUES(20,'P',76321,'Electronic Arts','36. Park Avenue','Building D','Redwood City','CA',305-555-0002,305-555-0012,'EA@example.com',100);
INSERT INTO CUSTOMER VALUES(30,'N',76321,'IBM','69. Hathaway Drive','Suite 58','Armonk','NY',305-555-0003,305-555-0013,'IDM@example.com',900);

INSERT INTO DISCOUNT_CODE VALUES('N',15);
INSERT INTO DISCOUNT_CODE VALUES('P',8);

INSERT INTO MANUFACTURER VALUES(666,'Lennox International Inc.','36. Beach Road','NONE','Richardson','TX',48963,306-555-0001,306-555-0011,'lennox@example.com','Todd Bluedorn');
INSERT INTO MANUFACTURER VALUES(999,'Skyworks Solutions Inc.','46. Sylvan Alley','Flor 22','Woburn','MA',52159,306-555-0002,306-555-0012,'skyworks@example.com','Bob Smith');

INSERT INTO MICRO_MARKET VALUES(76321,255.59,689.856,478.479);
INSERT INTO MICRO_MARKET VALUES(94043,157.869,385.821,147.538);









INSERT INTO  


COMMIT;
 